package com.dara.backgammon.ui

import android.os.*
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.*
import androidx.compose.foundation.gestures.detectHorizontalDragGestures
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.rotate
import androidx.compose.ui.platform.*
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.input.pointer.pointerInput
import com.dara.backgammon.R
import com.dara.backgammon.BuildConfig
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.*
import androidx.lifecycle.viewmodel.compose.viewModel
import com.dara.backgammon.ai.Difficulty
import com.dara.backgammon.core.*
import com.dara.backgammon.data.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.roundToInt

private val Gold=Color(0xffffd274);private val Glass=Color(0xcc11151b)
private fun Difficulty.fa()=when(this){Difficulty.BEGINNER->"تازه‌کار";Difficulty.EASY->"آسان";Difficulty.MEDIUM->"متوسط";Difficulty.HARD->"سخت";Difficulty.EXPERT->"حرفه‌ای"}
private fun BoardTheme.fa()=when(this){BoardTheme.PREMIUM_WOOD->"چوب ممتاز";BoardTheme.BRUSHED_METAL->"فلز برس‌خورده";BoardTheme.OBSIDIAN_IVORY->"ابسیدین و عاج";BoardTheme.CRYSTAL_GLASS->"شیشه کریستالی";BoardTheme.ROYAL_SAPPHIRE->"یاقوت سلطنتی"}
private fun PieceStyle.fa()=when(this){PieceStyle.KHATAM->"خاتم";PieceStyle.METAL->"فلزی";PieceStyle.OBSIDIAN_IVORY->"ابسیدین و عاج";PieceStyle.CRYSTAL->"کریستالی";PieceStyle.SAPPHIRE->"یاقوتی"}
private fun Player.fa()=if(this==Player.WHITE)"سفید" else "سیاه"
private fun DoublesRate.fa()=when(this){DoublesRate.NATURAL->"طبیعی";DoublesRate.REDUCED_20->"۲۰٪ کمتر";DoublesRate.REDUCED_50->"۵۰٪ کمتر";DoublesRate.NEVER->"بدون جفت"}
private fun tabFa(key:String)=when(key){"GAME"->"بازی";"AUDIO"->"صدا";"CONTROLS"->"کنترل‌ها";"APPEARANCE"->"ظاهر";"GUIDANCE"->"راهنما";"ABOUT"->"درباره";else->key}
@Composable fun BackgammonApp(vm:GameViewModel=viewModel()){
 val screen by vm.screen.collectAsState()
 MaterialTheme(colorScheme=darkColorScheme(primary=Gold,surface=Color(0xff11151b))){CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl){
  Box(Modifier.fillMaxSize().background(Brush.radialGradient(listOf(Color(0xff31483b),Color(0xff101d17))))){
   AnimatedContent(screen,transitionSpec={
    if(targetState.ordinal>initialState.ordinal)(slideInHorizontally(tween(480)){it}+fadeIn(tween(300))) togetherWith (slideOutHorizontally(tween(480)){-it/3}+fadeOut(tween(240)))
    else (slideInHorizontally(tween(480)){-it/2}+fadeIn(tween(300))) togetherWith (slideOutHorizontally(tween(480)){it}+fadeOut(tween(240)))
   },label="navigation"){destination->when(destination){Screen.MENU->MainMenu(vm);Screen.SETUP->SetupMenu(vm);Screen.GAME->GameScreen(vm)}}
  }
 }
 }
}
@Composable private fun Panel(modifier:Modifier=Modifier,content:@Composable ColumnScope.()->Unit)=Column(modifier.graphicsLayer{shadowElevation=24.dp.toPx();shape=RoundedCornerShape(18.dp);clip=false}.clip(RoundedCornerShape(18.dp)).background(Brush.verticalGradient(listOf(Color(0xe8292e31),Color(0xf4111518)))).border(1.dp,Color.White.copy(.18f),RoundedCornerShape(18.dp)).padding(18.dp),content=content)
@Composable private fun MainMenu(vm:GameViewModel){
 val s by vm.settings.collectAsState();val hasSaved by vm.hasSaved.collectAsState();var dialog by remember{mutableStateOf("")};val scene=when(s.tableScene){TableScene.DARK_GRASS->R.drawable.table_dark_grass;TableScene.STARRY_SKY->R.drawable.table_starry_sky;TableScene.AUTUMN_SUNSET->R.drawable.table_autumn_sunset;TableScene.PERSIAN_RUG->R.drawable.table_persian_rug;TableScene.DARK_RIVER->R.drawable.table_dark_river}
 Box(Modifier.fillMaxSize()){
  Image(painterResource(scene),null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop)
  Box(Modifier.fillMaxSize().background(Brush.horizontalGradient(listOf(Color(0xf40b0e10),Color(0xd51a1e20),Color(0x9c34393a),Color(0xb80b0e10)))))
  Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color.Black.copy(.18f),Color.Transparent,Color.Black.copy(.68f)))))
  Column(Modifier.align(Alignment.CenterStart).padding(start=48.dp).width(320.dp),horizontalAlignment=Alignment.Start){
   Text("♛",color=Color(0xffffd58a),fontSize=24.sp)
   Text("تخته نرد هوشمند",fontSize=30.sp,fontWeight=FontWeight.Black,letterSpacing=2.5.sp,color=Color(0xffffe2a5),style=androidx.compose.ui.text.TextStyle(shadow=androidx.compose.ui.graphics.Shadow(Color.Black,Offset(2f,3f),8f)))
   Text("راهبرد کلاسیک • تجربه‌ای هوشمند",fontSize=8.sp,fontWeight=FontWeight.Bold,letterSpacing=1.6.sp,color=Color.White.copy(.62f))
   Spacer(Modifier.height(24.dp))
   HeroMenuButton(if(hasSaved)"بازی جدید" else "شروع بازی","▷",true){vm.setup()}
   if(hasSaved){Spacer(Modifier.height(9.dp));HeroMenuButton("ادامه بازی","↻",false){vm.continueGame()}}
  }
  Row(Modifier.align(Alignment.BottomCenter).navigationBarsPadding().padding(start=30.dp,end=30.dp,bottom=16.dp).fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){
   LuxuryNav("♟","بازی با هوش مصنوعی",Modifier.weight(1f)){vm.setup()};LuxuryNav("♟♟","دو نفره محلی",Modifier.weight(1f)){vm.start(Mode.LOCAL)};LuxuryNav("◈","تخته‌ها و پوسته‌ها",Modifier.weight(1f)){dialog="themes"};LuxuryNav("⚙","تنظیمات",Modifier.weight(1f)){dialog="settings"}
  }
  Row(Modifier.align(Alignment.TopEnd).padding(top=12.dp,end=16.dp)){HomeIcon(if(s.sound)"🔊" else "🔇"){vm.update(s.copy(sound=!s.sound))};Spacer(Modifier.width(8.dp));HomeIcon("⚙"){dialog="settings"}}
 }
 if(dialog.isNotEmpty())Dialog(dialog,s,vm){dialog=""}
}
@Composable private fun HeroMenuButton(text:String,icon:String,primary:Boolean,go:()->Unit){val shape=RoundedCornerShape(6.dp);Row(Modifier.fillMaxWidth().height(52.dp).graphicsLayer{shadowElevation=if(primary)14.dp.toPx()else 6.dp.toPx();this.shape=shape;clip=false}.clip(shape).background(if(primary)Brush.horizontalGradient(listOf(Color(0xee4a4f51),Color(0xf0171a1d)))else Brush.horizontalGradient(listOf(Color(0xcc24282b),Color(0xee101316)))).border(1.dp,if(primary)Color(0xffffcf82).copy(.75f)else Color.White.copy(.24f),shape).clickable(onClick=go).padding(horizontal=17.dp),verticalAlignment=Alignment.CenterVertically){Text(icon,color=Color(0xffffd896),fontSize=22.sp);Spacer(Modifier.width(14.dp));Text(text,Modifier.weight(1f),color=Color(0xffffe6b4),fontWeight=FontWeight.Black,letterSpacing=1.2.sp);Text("›",color=Color(0xffffdc9c),fontSize=22.sp)}}
@Composable private fun LuxuryNav(icon:String,title:String,modifier:Modifier=Modifier,go:()->Unit){val shape=RoundedCornerShape(7.dp);Row(modifier.height(46.dp).clip(shape).background(Brush.verticalGradient(listOf(Color(0xaa23272b),Color(0xdd101316)))).border(1.dp,Color(0xffffd28a).copy(.28f),shape).clickable(onClick=go).padding(horizontal=13.dp),verticalAlignment=Alignment.CenterVertically){Text(icon,color=Color(0xffffd38c),fontSize=16.sp);Spacer(Modifier.width(9.dp));Text(title,color=Color.White.copy(.84f),fontSize=9.sp,fontWeight=FontWeight.Bold,letterSpacing=.7.sp)}}
@Composable private fun HomeIcon(icon:String,go:()->Unit){FilledTonalButton(go,contentPadding=PaddingValues(0.dp),modifier=Modifier.size(54.dp),shape=androidx.compose.foundation.shape.CircleShape,colors=ButtonDefaults.filledTonalButtonColors(containerColor=Color(0xdd2b332e),contentColor=Color.White)){Text(icon,fontSize=23.sp)}}
@Composable private fun SetupMenu(vm:GameViewModel){
 val s by vm.settings.collectAsState();var dialog by remember{mutableStateOf("")};val scene=when(s.tableScene){TableScene.DARK_GRASS->R.drawable.table_dark_grass;TableScene.STARRY_SKY->R.drawable.table_starry_sky;TableScene.AUTUMN_SUNSET->R.drawable.table_autumn_sunset;TableScene.PERSIAN_RUG->R.drawable.table_persian_rug;TableScene.DARK_RIVER->R.drawable.table_dark_river}
 Box(Modifier.fillMaxSize().pointerInput(Unit){var drag=0f;detectHorizontalDragGestures(onDragEnd={if(drag>120f)vm.menu();drag=0f},onHorizontalDrag={_,amount->drag+=amount})}){
  Image(painterResource(scene),null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.radialGradient(listOf(Color(0xb2454b4c),Color(0xee111618),Color(0xf4080b0d)))))
  Text("بازی جدید",Modifier.align(Alignment.TopCenter).padding(22.dp),fontSize=34.sp,fontWeight=FontWeight.Black,color=Color(0xffffdc83))
  Panel(Modifier.align(Alignment.Center).widthIn(420.dp,620.dp)){MenuAction("بازی با هوش مصنوعی","انتخاب از پنج سطح دشواری"){dialog="ai"};MenuAction("بازی دونفره محلی","بازی مشترک روی همین دستگاه"){vm.start(Mode.LOCAL)};Row{SmallAction("پوسته‌ها",Modifier.weight(1f)){dialog="themes"};Spacer(Modifier.width(10.dp));SmallAction("گزینه‌ها",Modifier.weight(1f)){dialog="settings"}};Spacer(Modifier.height(8.dp));TextButton({vm.menu()},Modifier.fillMaxWidth()){Text("بازگشت  ›",color=Color.White,fontWeight=FontWeight.Bold)}}
 }
 if(dialog.isNotEmpty())Dialog(dialog,s,vm){dialog=""}
}
@Composable private fun MenuAction(title:String,sub:String,go:()->Unit){val shape=RoundedCornerShape(14.dp);Row(Modifier.fillMaxWidth().height(68.dp).graphicsLayer{shadowElevation=9.dp.toPx();this.shape=shape;clip=false}.clip(shape).background(Brush.horizontalGradient(listOf(Color(0xee353a3d),Color(0xf21d2124),Color(0xee101315)))).border(1.2.dp,Color(0xffffd699).copy(.38f),shape).clickable(onClick=go).padding(horizontal=18.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(35.dp).clip(androidx.compose.foundation.shape.CircleShape).background(Color.Black.copy(.25f)).border(1.dp,Gold.copy(.55f),androidx.compose.foundation.shape.CircleShape),contentAlignment=Alignment.Center){Text(if(title.contains("AI"))"✦" else "●",color=Gold,fontSize=17.sp)};Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Text(title,color=Color(0xffffdfa0),fontWeight=FontWeight.Black,letterSpacing=1.1.sp);Text(sub,fontSize=10.sp,color=Color.White.copy(.62f))};Text("›",color=Gold,fontSize=25.sp)};Spacer(Modifier.height(11.dp))}
@Composable private fun SmallAction(t:String,m:Modifier=Modifier,go:()->Unit){OutlinedButton(go,m.height(44.dp),shape=RoundedCornerShape(11.dp),colors=ButtonDefaults.outlinedButtonColors(containerColor=Color(0xff202528).copy(.92f),contentColor=Color(0xffffd58b)),border=BorderStroke(1.dp,Color(0xffffc978).copy(.46f))){Text(t,fontSize=10.sp,fontWeight=FontWeight.Black,letterSpacing=.8.sp)}}
@Composable private fun Dialog(kind:String,s:Settings,vm:GameViewModel,close:()->Unit){
 var tab by remember(kind){mutableStateOf("GAME")};val context=LocalContext.current
 AlertDialog(onDismissRequest=close,modifier=Modifier.widthIn(min=680.dp,max=820.dp),shape=RoundedCornerShape(14.dp),containerColor=Color(0xf015181b),tonalElevation=24.dp,
  title={Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(if(kind=="settings")"تنظیمات بازی" else when(kind){"ai"->"انتخاب سطح دشواری";"themes"->"مجموعه تخته‌ها";"stats"->"آمار بازی";else->"تخته نرد هوشمند"},Modifier.weight(1f),color=Color(0xffffdda0),fontWeight=FontWeight.Black,letterSpacing=1.2.sp);TextButton(close){Text("×",fontSize=25.sp,color=Color.White.copy(.72f))}}},
  text={if(kind=="settings")Row(Modifier.fillMaxWidth().height(370.dp).clip(RoundedCornerShape(10.dp)).background(Color(0x66101518)).border(1.dp,Color.White.copy(.10f),RoundedCornerShape(10.dp))){
    Column(Modifier.width(165.dp).fillMaxHeight().background(Brush.verticalGradient(listOf(Color(0xdd25201c),Color(0xee111316)))).padding(9.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text("♛  تخته نرد هوشمند",Modifier.padding(10.dp),color=Color(0xffffd797),fontSize=10.sp,fontWeight=FontWeight.Black);listOf("GAME" to "⚄","AUDIO" to "♪","APPEARANCE" to "◈","GUIDANCE" to "✦","ABOUT" to "ⓘ").forEach{(name,icon)->StudioTab(icon,tabFa(name),tab==name){tab=name}}}
    Column(Modifier.weight(1f).fillMaxHeight().verticalScroll(rememberScrollState()).padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
     Text(when(tab){"AUDIO"->"صدا و بازخورد";"APPEARANCE"->"ظاهر بازی";"GUIDANCE"->"راهنمای حرکت";"ABOUT"->"درباره برنامه";else->"شیوه بازی"},color=Color(0xffffd99a),fontWeight=FontWeight.Black,fontSize=15.sp)
     Text(when(tab){"AUDIO"->"صدا و بازخورد لمسی";"APPEARANCE"->"انتخاب تخته و مجموعه مهره";"GUIDANCE"->"نحوه نمایش حرکت‌های مجاز";"ABOUT"->"اطلاعات ناشر و خدمات فروشگاه";else->"قوانین بازی و قدرت هوش مصنوعی"},color=Color.White.copy(.44f),fontSize=9.sp)
     when(tab){
      "ABOUT"->{AboutAndStore(context)}
      "AUDIO"->{SettingToggle("افکت‌های صوتی","صدای طبیعی تاس و مهره",s.sound){vm.update(s.copy(sound=it))};SettingToggle("بازخورد لرزشی","واکنش لمسی هنگام بازی",s.vibration){vm.update(s.copy(vibration=it))};SettingToggle("پویانمایی کامل","حرکت کامل و نرم مهره و تاس",s.animations){vm.update(s.copy(animations=it))}}
      "APPEARANCE"->{Text("پوسته تخته",fontSize=9.sp,color=Gold);BoardTheme.entries.forEach{Choice(it.fa(),it==s.theme){vm.update(s.copy(theme=it,pieces=it.defaultPieces()))}};Text("مجموعه مهره‌ها",fontSize=9.sp,color=Gold);PieceStyle.entries.forEach{Choice(it.fa(),it==s.pieces){vm.update(s.copy(pieces=it))}}}
      "GUIDANCE"->GuidanceMode.entries.forEach{Choice(if(it==GuidanceMode.SIMPLE)"ساده — مقصدهای مستقیم" else "مربی — مسیرهای ترکیبی کامل",it==s.guidanceMode){vm.update(s.copy(guidanceMode=it))}}
      else->{Text("قدرت هوش مصنوعی",fontSize=9.sp,color=Gold);Difficulty.entries.forEach{Choice(it.fa(),it==s.difficulty){vm.update(s.copy(difficulty=it))}};Text("ساعت مسابقه",fontSize=9.sp,color=Gold);ClockPreset.entries.forEach{Choice(when(it){ClockPreset.OFF->"خاموش";ClockPreset.RAPID_60->"سریع — ۱ دقیقه ذخیره / ۱۰ ثانیه هر نوبت";ClockPreset.STANDARD_180->"استاندارد — ۳ دقیقه ذخیره / ۲۰ ثانیه هر نوبت"},it==s.clockPreset){vm.update(s.copy(clockPreset=it))}}}
     }
    }
   }else Column(Modifier.heightIn(max=420.dp).verticalScroll(rememberScrollState())){when(kind){"ai"->{Text("برای شروع یک سطح را انتخاب کنید",fontSize=9.sp,color=Gold);Difficulty.entries.forEach{Choice(it.fa(),it==s.difficulty){vm.update(s.copy(difficulty=it));vm.start(Mode.AI)}}};"themes"->BoardTheme.entries.forEach{Choice(it.fa(),it==s.theme){vm.update(s.copy(theme=it,pieces=it.defaultPieces()))}};"stats"->Text("آمار مسابقه فقط روی دستگاه ذخیره می‌شود.",color=Color.White.copy(.7f));else->Text("یک تجربه کاملاً آفلاین و اختصاصی از تخته‌نرد.")}}},
  confirmButton={if(kind!="settings")TextButton(close){Text("بستن",color=Color(0xffffd99a))}})
}
@Composable private fun StudioTab(icon:String,title:String,on:Boolean,go:()->Unit){Row(Modifier.fillMaxWidth().height(45.dp).clip(RoundedCornerShape(7.dp)).background(if(on)Brush.horizontalGradient(listOf(Color(0xffa26839),Color(0xff39241a)))else Brush.horizontalGradient(listOf(Color.Transparent,Color.Transparent))).border(if(on)1.dp else 0.dp,if(on)Color(0xffffd18b).copy(.55f)else Color.Transparent,RoundedCornerShape(7.dp)).clickable(onClick=go).padding(horizontal=11.dp),verticalAlignment=Alignment.CenterVertically){Text(icon,color=if(on)Color(0xffffdc9b)else Color.White.copy(.55f));Spacer(Modifier.width(10.dp));Text(title,color=if(on)Color(0xffffe1ad)else Color.White.copy(.70f),fontSize=10.sp,fontWeight=FontWeight.Bold)}}
@Composable private fun SettingToggle(title:String,sub:String,value:Boolean,set:(Boolean)->Unit){Row(Modifier.fillMaxWidth().height(58.dp).clip(RoundedCornerShape(8.dp)).background(Color.White.copy(.035f)).border(1.dp,Color.White.copy(.08f),RoundedCornerShape(8.dp)).clickable{set(!value)}.padding(horizontal=13.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,color=Color.White.copy(.88f),fontSize=10.sp,fontWeight=FontWeight.Bold);Text(sub,color=Color.White.copy(.40f),fontSize=8.sp)};Switch(value,set,colors=SwitchDefaults.colors(checkedThumbColor=Color(0xffffe0a0),checkedTrackColor=Color(0xffa3693d)))}}
@Composable private fun Choice(t:String,on:Boolean=false,go:()->Unit){val shape=RoundedCornerShape(10.dp);Row(Modifier.fillMaxWidth().padding(vertical=3.dp).heightIn(min=43.dp).clip(shape).background(if(on)Brush.horizontalGradient(listOf(Color(0xff555b5d),Color(0xff24282b)))else Brush.horizontalGradient(listOf(Color(0xff241915),Color(0xff1c1513)))).border(if(on)1.4.dp else .8.dp,if(on)Gold.copy(.78f)else Color.White.copy(.13f),shape).clickable(onClick=go).padding(horizontal=14.dp,vertical=9.dp),verticalAlignment=Alignment.CenterVertically){Text(if(on)"◆" else "◇",color=if(on)Gold else Color.White.copy(.28f),fontSize=10.sp);Spacer(Modifier.width(10.dp));Text(t,Modifier.weight(1f),color=if(on)Color(0xffffdda0)else Color.White.copy(.84f),fontSize=11.sp,fontWeight=if(on)FontWeight.Black else FontWeight.SemiBold);Text("›",color=if(on)Gold else Color.White.copy(.25f),fontSize=18.sp)}}
@Composable private fun SwitchRow(t:String,v:Boolean,set:(Boolean)->Unit)=Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(t,Modifier.weight(1f));Switch(v,set)}

@Composable private fun GameScreen(vm:GameViewModel){val game by vm.game.collectAsState();val settings by vm.settings.collectAsState();val rolling by vm.rolling.collectAsState();val match by vm.match.collectAsState();val autoAssist by vm.autoAssist.collectAsState();val clock by vm.clock.collectAsState();var selected by remember(game.position,game.dice){mutableStateOf<Int?>(null)};var panel by remember{mutableStateOf("")};val legal=remember(game,match.thinking){if(match.thinking||(vm.mode==Mode.AI&&game.position.turn==Player.BLACK))emptyList() else GameEngine.legalMoves(game.position,game.dice)};val context=LocalContext.current
 fun haptic(){if(settings.vibration){val v=context.getSystemService(android.os.Vibrator::class.java);if(Build.VERSION.SDK_INT>=26)v?.vibrate(VibrationEffect.createOneShot(22,70))else @Suppress("DEPRECATION")v?.vibrate(22)}}
 val palette=boardPalette(settings.theme);val background=when(settings.tableScene){TableScene.DARK_GRASS->R.drawable.table_dark_grass;TableScene.STARRY_SKY->R.drawable.table_starry_sky;TableScene.AUTUMN_SUNSET->R.drawable.table_autumn_sunset;TableScene.PERSIAN_RUG->R.drawable.table_persian_rug;TableScene.DARK_RIVER->R.drawable.table_dark_river}
 fun cycleScene(step:Int){val all=TableScene.entries;val next=all[(all.indexOf(settings.tableScene)+step+all.size)%all.size];vm.update(settings.copy(tableScene=next))}
 BoxWithConstraints(Modifier.fillMaxSize()){
  val layout=boardLayoutProfile(maxWidth.value,maxHeight.value);val shell=boardPalette(settings.theme)
  Image(painterResource(background),null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Color.Black.copy(.06f)))
  Box(Modifier.align(Alignment.Center).fillMaxWidth(layout.widthFraction).fillMaxHeight(layout.heightFraction).absoluteOffset(y=13.dp).clip(RoundedCornerShape(15.dp)).background(shell.frameDark).border(2.dp,Color.Black.copy(.75f),RoundedCornerShape(15.dp)))
  Box(Modifier.align(Alignment.Center).fillMaxWidth(layout.widthFraction).fillMaxHeight(layout.heightFraction).absoluteOffset(y=7.dp).clip(RoundedCornerShape(14.dp)).background(Brush.verticalGradient(listOf(shell.frame,shell.frameDark))).border(1.dp,shell.light.copy(.46f),RoundedCornerShape(14.dp)))
  BoxWithConstraints(Modifier.align(Alignment.Center).fillMaxWidth(layout.widthFraction).fillMaxHeight(layout.heightFraction).graphicsLayer{shadowElevation=34.dp.toPx();shape=RoundedCornerShape(13.dp);clip=false}.clip(RoundedCornerShape(13.dp)).background(Brush.verticalGradient(listOf(shell.frame.copy(.92f),shell.frameDark))).border(1.dp,shell.light.copy(.52f),RoundedCornerShape(13.dp))){
   FlatBoard(game,settings.theme,settings.pieces,selected,legal,{selected=it;haptic()},{vm.move(it);selected=null;haptic()},{from,to->vm.moveCombined(from,to).also{if(it){selected=null;haptic()}}},Modifier.fillMaxSize().padding(top=30.dp,start=3.dp,end=3.dp,bottom=3.dp),scene=settings.tableScene,guidance=settings.guidanceMode)
   if(clock.active)ClockSettingsButton({panel="settings"},Modifier.align(Alignment.TopStart).padding(start=8.dp,top=1.dp)) else TopGameBar(settings.difficulty,false,if(match.thinking)"هوش مصنوعی در حال فکر" else if(rolling)"پرتاب تاس" else if(vm.mode==Mode.LOCAL)"نوبت ${game.position.turn.fa()}" else if(game.position.turn==Player.WHITE)"نوبت شما" else "نوبت هوش مصنوعی",{panel="settings"},Modifier.align(Alignment.TopCenter))
   val canDouble=match.cube<64&&!game.rolled&&!rolling&&!match.thinking&&game.winner==null&&(vm.mode==Mode.LOCAL||game.position.turn==Player.WHITE)&&match.pendingDoubleBy==null&&(match.cubeOwner==null||match.cubeOwner==game.position.turn)
   val cubeY by animateDpAsState(if(match.cubeOwner==Player.WHITE&&match.pendingDoubleBy==null)maxHeight-45.dp else 6.dp,tween(620,easing=FastOutSlowInEasing),label="cubeDock")
   AxleDoublingCube(match.cube,match.cubeOwner,match.pendingDoubleBy,canDouble,{vm.offerDouble()},Modifier.align(Alignment.TopCenter).offset(y=cubeY))
   Row(Modifier.align(Alignment.Center).absoluteOffset(x=layout.actionOffsetDp.dp),horizontalArrangement=Arrangement.spacedBy(6.dp),verticalAlignment=Alignment.CenterVertically){if(vm.mode==Mode.AI&&((game.rolled&&!rolling&&game.position.turn==Player.WHITE)||autoAssist))EngravedWoodAction(if(autoAssist)"خودکار روشن" else "خودکار خاموش"){vm.toggleAutoAssist()};BarEngraving("بازگردانی"){vm.undo()}}

  }
  if(clock.active)MatchClocks(clock,game.position.turn,Modifier.align(Alignment.TopCenter).fillMaxWidth(.62f).padding(top=7.dp))
  CarvedScoreCounter(match.whiteScore,match.blackScore,Modifier.align(Alignment.TopCenter).padding(top=2.dp))
  if(game.dice.isNotEmpty()||rolling||(!game.rolled&&!(vm.mode==Mode.AI&&game.position.turn==Player.BLACK))) AnimatedDice(game.dice,when(settings.theme){BoardTheme.PREMIUM_WOOD->if(game.position.turn==Player.WHITE)DiceStyle.CLASSIC else DiceStyle.ONYX;BoardTheme.BRUSHED_METAL->if(game.position.turn==Player.WHITE)DiceStyle.GOLD else DiceStyle.SILVER;BoardTheme.OBSIDIAN_IVORY->if(game.position.turn==Player.WHITE)DiceStyle.MARBLE_LIGHT else DiceStyle.MARBLE_DARK;BoardTheme.CRYSTAL_GLASS->if(game.position.turn==Player.WHITE)DiceStyle.GLASS_LIGHT else DiceStyle.GLASS_DARK;BoardTheme.ROYAL_SAPPHIRE->if(game.position.turn==Player.WHITE)DiceStyle.GLASS_LIGHT else DiceStyle.SAPPHIRE},rolling,{vm.roll();haptic()},Modifier.align(Alignment.Center).absoluteOffset(x=layout.diceOffsetDp.dp))
  SceneArrow("‹",Modifier.align(Alignment.CenterStart).padding(start=8.dp)){cycleScene(-1)}
  SceneArrow("›",Modifier.align(Alignment.CenterEnd).padding(end=8.dp)){cycleScene(1)}
 }
 AnimatedVisibility(panel.isNotEmpty(),enter=fadeIn(tween(260))+scaleIn(tween(320),initialScale=.96f),exit=fadeOut(tween(220))+scaleOut(tween(220),targetScale=.97f)){if(panel=="settings")InGameSettingsStudio(settings,match,vm){panel=""}else GameDrawer(panel,settings,match,vm,{panel=""},{panel=it})}
 match.pendingDoubleBy?.takeIf{vm.mode==Mode.LOCAL||it==Player.BLACK}?.let{offerer->AlertDialog(onDismissRequest={},title={Text("پیشنهاد دوبرابر از ${offerer.fa()} تا ×${match.cube*2}")},text={Text("بازیکن ${offerer.other().fa()} می‌تواند پیشنهاد را قبول کند و مالک مکعب شود، یا آن را رد کند و بازی را با امتیاز فعلی واگذار کند.")},confirmButton={Button({vm.acceptDouble()}){Text("قبول")}},dismissButton={OutlinedButton({vm.declineDouble()}){Text("رد")}})}
 game.winner?.let{w->val loser=w.other();val local=vm.mode==Mode.LOCAL;val won=w==Player.WHITE;val result=if(match.timedOutBy!=null)"زمان بازیکن تمام شد" else if(match.droppedBy!=null)"پیشنهاد دوبرابر رد شد — بازی ${match.cube} امتیازی" else when{game.position.off(loser)>0->"برد معمولی";game.position.bar(loser)>0->"بک‌گمون";else->"گمون"};AlertDialog({},icon={Text(if(won)"✦" else "◆",fontSize=42.sp,color=if(won)Color(0xffffd36a)else Color(0xffb87a69))},title={Text(if(local)"${w.fa()} برنده شد" else if(won)"پیروزی" else "شکست",color=Color(0xffffdda0),fontWeight=FontWeight.Black,letterSpacing=2.sp)},text={Column(horizontalAlignment=Alignment.CenterHorizontally){Text(if(local)"پایانی قاطع برای بازیکن ${w.fa()}." else if(won)"یک پایان استادانه." else "این دور به حریف رسید.",color=Color.White.copy(.78f),textAlign=TextAlign.Center);Spacer(Modifier.height(10.dp));Text("$result\nامتیاز  ${match.whiteScore} — ${match.blackScore}",color=Color(0xffffd59a),textAlign=TextAlign.Center,fontWeight=FontWeight.Bold)}},confirmButton={Button({vm.restart()},colors=ButtonDefaults.buttonColors(Color(0xff8a522f))){Text("بازی دوباره")}},dismissButton={TextButton({vm.menu()}){Text("خروج",color=Color(0xffffd59a))}},containerColor=Color(0xff32170f),tonalElevation=18.dp,shape=RoundedCornerShape(16.dp))}
}
@Composable private fun InGameSettingsStudio(s:Settings,match:MatchInfo,vm:GameViewModel,close:()->Unit){
 var tab by remember{mutableStateOf("GAME")};val interaction=remember{MutableInteractionSource()};val context=LocalContext.current
 Box(Modifier.fillMaxSize().background(Color.Black.copy(.48f)).clickable(onClick=close),contentAlignment=Alignment.Center){
  Row(Modifier.fillMaxWidth(.78f).fillMaxHeight(.78f).graphicsLayer{shadowElevation=32.dp.toPx();shape=RoundedCornerShape(18.dp);clip=false}.clip(RoundedCornerShape(18.dp)).background(Brush.linearGradient(listOf(Color(0xed22272a),Color(0xf5121619),Color(0xe922272a)))).border(1.2.dp,Color.White.copy(.20f),RoundedCornerShape(18.dp)).clickable(interactionSource=interaction,indication=null,onClick={}),verticalAlignment=Alignment.Top){
   Column(Modifier.width(190.dp).fillMaxHeight().background(Brush.verticalGradient(listOf(Color(0xe72b3032),Color(0xf0121618)))).border(0.dp,Color.Transparent).padding(12.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){
    Column(Modifier.fillMaxWidth().padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("♛",color=Color(0xffffd38d),fontSize=20.sp);Text("تخته نرد هوشمند",color=Color(0xffffdda2),fontSize=11.sp,fontWeight=FontWeight.Black,letterSpacing=.8.sp);Text("تنظیمات مسابقه",color=Color.White.copy(.38f),fontSize=7.sp,letterSpacing=1.4.sp)}
    listOf("GAME" to "⚄","AUDIO" to "♪","CONTROLS" to "☝","APPEARANCE" to "◈","ABOUT" to "ⓘ").forEach{(name,icon)->StudioTab(icon,tabFa(name),tab==name){tab=name}}
    Spacer(Modifier.weight(1f));Text("امتیاز  ${match.whiteScore} — ${match.blackScore}",Modifier.fillMaxWidth().padding(10.dp),color=Color.White.copy(.45f),fontSize=9.sp,textAlign=TextAlign.Center)
   }
   Column(Modifier.weight(1f).fillMaxHeight().padding(22.dp)){
    Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(when(tab){"AUDIO"->"صدا و حس بازی";"CONTROLS"->"کنترل‌ها";"APPEARANCE"->"ظاهر بازی";"ABOUT"->"درباره برنامه";else->"تنظیمات بازی"},color=Color(0xffffdda0),fontSize=20.sp,fontWeight=FontWeight.Bold);Text(when(tab){"AUDIO"->"صدای طبیعی و بازخورد لمسی";"CONTROLS"->"کمک حرکتی و بازخورد تخته";"APPEARANCE"->"جنس تخته و مجموعه مهره";"ABOUT"->"ناشر و خدمات فروشگاه";else->"رفتار مسابقه و قدرت هوش مصنوعی"},color=Color.White.copy(.43f),fontSize=9.sp)};Box(Modifier.size(32.dp).clip(RoundedCornerShape(8.dp)).border(1.dp,Color(0xffffd18a).copy(.42f),RoundedCornerShape(8.dp)).clickable(onClick=close),contentAlignment=Alignment.Center){Text("×",color=Color(0xffffdda0),fontSize=20.sp)}}
    Spacer(Modifier.height(16.dp));Box(Modifier.fillMaxWidth().height(1.dp).background(Color.White.copy(.10f)));Spacer(Modifier.height(8.dp))
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(2.dp)){
     when(tab){
      "ABOUT"->{AboutAndStore(context)}
      "AUDIO"->{StudioToggleRow("افکت‌های صوتی","صدای تاس، مهره و رابط",s.sound){vm.update(s.copy(sound=it))};StudioToggleRow("بازخورد لرزشی","واکنش لمسی هنگام بازی",s.vibration){vm.update(s.copy(vibration=it))}}
      "CONTROLS"->{StudioSelectorRow("راهنمای حرکت",if(s.guidanceMode==GuidanceMode.SIMPLE)"ساده" else "مربی",{val all=GuidanceMode.entries;vm.update(s.copy(guidanceMode=all[(all.indexOf(s.guidanceMode)-1+all.size)%all.size]))},{val all=GuidanceMode.entries;vm.update(s.copy(guidanceMode=all[(all.indexOf(s.guidanceMode)+1)%all.size]))});StudioToggleRow("پویانمایی کامل","حرکت نرم تاس و مهره",s.animations){vm.update(s.copy(animations=it))}}
      "APPEARANCE"->{StudioSelectorRow("پوسته تخته",s.theme.fa(),{val all=BoardTheme.entries;val t=all[(all.indexOf(s.theme)-1+all.size)%all.size];vm.update(s.copy(theme=t,pieces=t.defaultPieces()))},{val all=BoardTheme.entries;val t=all[(all.indexOf(s.theme)+1)%all.size];vm.update(s.copy(theme=t,pieces=t.defaultPieces()))});StudioSelectorRow("مجموعه مهره‌ها",s.pieces.fa(),{val all=PieceStyle.entries;vm.update(s.copy(pieces=all[(all.indexOf(s.pieces)-1+all.size)%all.size]))},{val all=PieceStyle.entries;vm.update(s.copy(pieces=all[(all.indexOf(s.pieces)+1)%all.size]))})}
      else->{StudioSelectorRow("قدرت هوش مصنوعی",s.difficulty.fa(),{val all=Difficulty.entries;vm.update(s.copy(difficulty=all[(all.indexOf(s.difficulty)-1+all.size)%all.size]))},{val all=Difficulty.entries;vm.update(s.copy(difficulty=all[(all.indexOf(s.difficulty)+1)%all.size]))});StudioSelectorRow("ساعت مسابقه",when(s.clockPreset){ClockPreset.OFF->"خاموش";ClockPreset.RAPID_60->"سریع";ClockPreset.STANDARD_180->"استاندارد"},{val all=ClockPreset.entries;vm.update(s.copy(clockPreset=all[(all.indexOf(s.clockPreset)-1+all.size)%all.size]))},{val all=ClockPreset.entries;vm.update(s.copy(clockPreset=all[(all.indexOf(s.clockPreset)+1)%all.size]))});StudioSelectorRow("احتمال جفت",s.doublesRate.fa(),{val all=DoublesRate.entries;vm.update(s.copy(doublesRate=all[(all.indexOf(s.doublesRate)-1+all.size)%all.size]))},{val all=DoublesRate.entries;vm.update(s.copy(doublesRate=all[(all.indexOf(s.doublesRate)+1)%all.size]))})}
     }
    }
   }
  }
 }
}
@Composable private fun StudioSelectorRow(title:String,value:String,previous:()->Unit,next:()->Unit){Row(Modifier.fillMaxWidth().height(58.dp).border(BorderStroke(1.dp,Color.White.copy(.08f))).padding(horizontal=8.dp),verticalAlignment=Alignment.CenterVertically){Text(title,Modifier.weight(1f),color=Color.White.copy(.82f),fontSize=11.sp);Box(Modifier.size(30.dp).clip(RoundedCornerShape(7.dp)).clickable(onClick=previous),contentAlignment=Alignment.Center){Text("‹",color=Color(0xffffd493),fontSize=20.sp)};Box(Modifier.widthIn(min=150.dp).height(34.dp).clip(RoundedCornerShape(8.dp)).background(Color(0xff0d1114)).border(1.dp,Color.White.copy(.12f),RoundedCornerShape(8.dp)),contentAlignment=Alignment.Center){Text(value,color=Color(0xffffdfa5),fontSize=9.sp,fontWeight=FontWeight.Bold)};Box(Modifier.size(30.dp).clip(RoundedCornerShape(7.dp)).clickable(onClick=next),contentAlignment=Alignment.Center){Text("›",color=Color(0xffffd493),fontSize=20.sp)}}}
@Composable private fun StudioToggleRow(title:String,sub:String,value:Boolean,set:(Boolean)->Unit){Row(Modifier.fillMaxWidth().height(64.dp).border(BorderStroke(1.dp,Color.White.copy(.08f))).clickable{set(!value)}.padding(horizontal=8.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,color=Color.White.copy(.84f),fontSize=11.sp);Text(sub,color=Color.White.copy(.38f),fontSize=8.sp)};Switch(value,set,colors=SwitchDefaults.colors(checkedThumbColor=Color.White,checkedTrackColor=Color(0xffb8804c),uncheckedThumbColor=Color(0xff777d80),uncheckedTrackColor=Color(0xff272d30)))} }
@Composable private fun AboutAndStore(context:android.content.Context){Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(9.dp)){Text("تخته نرد هوشمند",color=Color(0xffffdda0),fontSize=16.sp,fontWeight=FontWeight.Black);Text("طراحی، توسعه، ویرایش و عرضه: وحید مهرابادی",color=Color.White.copy(.78f),fontSize=10.sp);Text("نسخه ${BuildConfig.VERSION_NAME} • ویژه ${BuildConfig.STORE_NAME}",color=Color.White.copy(.46f),fontSize=9.sp);SettingAction("پشتیبانی","ارسال پیام به پشتیبانی؛ نشانی ایمیل در برنامه نمایش داده نمی‌شود"){MarketActions.support(context)};SettingAction("بررسی به‌روزرسانی","بررسی نسخه جدید در ${BuildConfig.STORE_NAME}"){MarketActions.checkUpdate(context)};SettingAction("صفحه برنامه در ${BuildConfig.STORE_NAME}","مشاهده صفحه رسمی برنامه"){MarketActions.openStorePage(context)};SettingAction("ثبت امتیاز و دیدگاه","ارسال نظر در ${BuildConfig.STORE_NAME}"){MarketActions.rate(context)}}}
@Composable private fun SettingAction(title:String,sub:String,go:()->Unit){Row(Modifier.fillMaxWidth().height(54.dp).clip(RoundedCornerShape(8.dp)).background(Color.White.copy(.035f)).border(1.dp,Color.White.copy(.09f),RoundedCornerShape(8.dp)).clickable(onClick=go).padding(horizontal=13.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,color=Color.White.copy(.88f),fontSize=10.sp,fontWeight=FontWeight.Bold);Text(sub,color=Color.White.copy(.42f),fontSize=8.sp)};Text("‹",color=Color(0xffffd493),fontSize=20.sp)}}
@Composable private fun GameDrawer(kind:String,s:Settings,match:MatchInfo,vm:GameViewModel,close:()->Unit,switch:(String)->Unit){
 Box(Modifier.fillMaxSize().background(Color.Black.copy(.24f)).clickable(onClick=close)){
  AnimatedContent(kind,modifier=Modifier.align(Alignment.CenterEnd).widthIn(min=340.dp,max=400.dp).padding(end=18.dp),transitionSpec={slideInHorizontally(tween(330)){it}+fadeIn() togetherWith slideOutHorizontally(tween(250)){it}+fadeOut()},label="woodMenu"){page->
   Column(Modifier.heightIn(max=530.dp).clip(RoundedCornerShape(16.dp)).background(Brush.verticalGradient(listOf(Color(0xee272c2f),Color(0xf2111518)))).border(1.dp,Color.White.copy(.16f),RoundedCornerShape(16.dp)).verticalScroll(rememberScrollState()).padding(12.dp),horizontalAlignment=Alignment.End,verticalArrangement=Arrangement.spacedBy(7.dp)){
    val nested=page in listOf("themes","pieces","difficulty","sound","dice","clock","guidance")
    WoodMenuPlank(if(nested)"‹  SETTINGS" else when(page){"menu"->"منوی مسابقه";else->"تنظیمات بازی"},"امتیاز ${match.whiteScore} — ${match.blackScore}",large=true){if(nested)switch("settings")else close()}
    when(page){
     "menu"->{WoodMenuPlank("ادامه","بازگشت به تخته",go=close);WoodMenuPlank("بازگردانی حرکت","بازگرداندن وضعیت قبلی"){vm.undo();close()};WoodMenuPlank("منوی اصلی","خروج از مسابقه"){vm.menu()}}
     "themes"->BoardTheme.entries.forEach{t->WoodMenuPlank(t.fa(),if(t==s.theme)"◆  انتخاب‌شده — تاس و مهره هماهنگ" else "مجموعه تخته، تاس و مهره پیش‌فرض"){vm.update(s.copy(theme=t,pieces=t.defaultPieces()))}}
     "pieces"->PieceStyle.entries.forEach{piece->WoodMenuPlank(piece.fa(),if(piece==s.pieces)"◆  انتخاب‌شده" else "مجموعه مهره‌ها"){vm.update(s.copy(pieces=piece))}}
     "difficulty"->Difficulty.entries.forEach{d->WoodMenuPlank(d.fa(),if(d==s.difficulty)"◆  انتخاب‌شده" else "قدرت هوش مصنوعی"){vm.update(s.copy(difficulty=d))}}
     "sound"->{WoodTogglePlank("افکت‌های صوتی",s.sound){vm.update(s.copy(sound=it))};WoodTogglePlank("بازخورد لرزشی",s.vibration){vm.update(s.copy(vibration=it))};WoodTogglePlank("پویانمایی نرم",s.animations){vm.update(s.copy(animations=it))}}
     "dice"->{val labels=mapOf(DoublesRate.NATURAL to "حالت طبیعی • ۸٫۳٪",DoublesRate.REDUCED_20 to "۲۰٪ کمتر • ۶٫۷٪",DoublesRate.REDUCED_50 to "۵۰٪ کمتر • ۴٫۲٪",DoublesRate.NEVER to "بدون جفت • ۰٪");DoublesRate.entries.forEach{rate->WoodMenuPlank(labels[rate]!!,if(rate==s.doublesRate)"◆  انتخاب‌شده — برای هر دو بازیکن یکسان" else "قانون یکسان برای بازیکن و هوش مصنوعی"){vm.update(s.copy(doublesRate=rate))}}}
     "clock"->{val labels=mapOf(ClockPreset.OFF to ("ساعت خاموش" to "بازی آزاد بدون محدودیت زمان"),ClockPreset.RAPID_60 to ("سریع • ذخیره ۱ دقیقه" to "۱۰ ثانیه در هر نوبت"),ClockPreset.STANDARD_180 to ("استاندارد • ذخیره ۳ دقیقه" to "۲۰ ثانیه در هر نوبت"));ClockPreset.entries.forEach{preset->val text=labels[preset]!!;WoodMenuPlank(text.first,if(preset==s.clockPreset)"◆  انتخاب‌شده — ${text.second}" else text.second){vm.update(s.copy(clockPreset=preset))}}}
     "guidance"->{WoodMenuPlank("راهنمای ساده",if(s.guidanceMode==GuidanceMode.SIMPLE)"◆  انتخاب‌شده — فقط حرکت مستقیم" else "نمایش یک گام مجاز"){vm.update(s.copy(guidanceMode=GuidanceMode.SIMPLE))};WoodMenuPlank("راهنمای مربی",if(s.guidanceMode==GuidanceMode.COACH)"◆  انتخاب‌شده — مسیرهای کامل" else "مسیرهای ترکیبی آموزشی"){vm.update(s.copy(guidanceMode=GuidanceMode.COACH))}}
     else->{WoodMenuPlank("صدا و حس بازی",if(s.sound)"صدا روشن" else "صدا خاموش"){switch("sound")};WoodMenuPlank("ساعت مسابقه",when(s.clockPreset){ClockPreset.OFF->"خاموش";ClockPreset.RAPID_60->"ذخیره ۱ دقیقه • نوبت ۱۰ ثانیه";ClockPreset.STANDARD_180->"ذخیره ۳ دقیقه • نوبت ۲۰ ثانیه"}){switch("clock")};WoodMenuPlank("راهنمای حرکت",if(s.guidanceMode==GuidanceMode.SIMPLE)"ساده • فقط حرکت بعدی" else "مربی • مسیرهای کامل"){switch("guidance")};WoodMenuPlank("تاس — جفت‌ها",when(s.doublesRate){DoublesRate.NATURAL->"حالت طبیعی • ۸٫۳٪";DoublesRate.REDUCED_20->"۲۰٪ کمتر • ۶٫۷٪";DoublesRate.REDUCED_50->"۵۰٪ کمتر • ۴٫۲٪";DoublesRate.NEVER->"جفت غیرفعال"}){switch("dice")};WoodMenuPlank("پوسته تخته",s.theme.fa()){switch("themes")};WoodMenuPlank("مجموعه مهره‌ها",s.pieces.fa()){switch("pieces")};WoodMenuPlank("قدرت هوش مصنوعی",s.difficulty.fa()){switch("difficulty")}}
    }
   }
  }
 }
}
@Composable private fun WoodMenuPlank(title:String,sub:String="",large:Boolean=false,go:()->Unit){
 val shape=RoundedCornerShape(topStart=12.dp,bottomStart=12.dp,topEnd=4.dp,bottomEnd=4.dp);val interaction=remember{MutableInteractionSource()};val pressed by interaction.collectIsPressedAsState();val selected=sub.startsWith("◆")
 val scale by animateFloatAsState(if(pressed)1.045f else if(selected)1.022f else 1f,tween(110),label="plankScale");val shift by animateFloatAsState(if(pressed)-11f else if(selected)-6f else 0f,tween(140),label="plankShift")
 Column(Modifier.width(if(large)310.dp else 282.dp).height(if(large)62.dp else 54.dp).graphicsLayer{scaleX=scale;scaleY=scale;translationX=shift.dp.toPx();shadowElevation=(if(pressed)20 else if(selected)16 else 12).dp.toPx();this.shape=shape;clip=false}.clip(shape).background(Brush.horizontalGradient(if(selected)listOf(Color(0xff555b5d),Color(0xff252a2d))else listOf(Color(0xff252a2d),Color(0xff171b1e)))).border(if(selected)1.4.dp else 1.dp,if(selected)Color(0xffffd28b).copy(.72f)else Color.White.copy(.10f),shape).clickable(interactionSource=interaction,indication=null,onClick=go).padding(horizontal=18.dp,vertical=9.dp)){
  Text(title,color=Color(0xffffdda0),fontWeight=FontWeight.Black,fontSize=if(large)14.sp else 12.sp,letterSpacing=.8.sp)
  if(sub.isNotEmpty())Text(sub,color=Color(0xffffead0).copy(if(selected).86f else .68f),fontSize=9.sp)
 }
}
@Composable private fun WoodTogglePlank(title:String,value:Boolean,set:(Boolean)->Unit){
val shape=RoundedCornerShape(8.dp)
 Row(Modifier.width(282.dp).height(54.dp).graphicsLayer{shadowElevation=8.dp.toPx();this.shape=shape;clip=false}.clip(shape).background(Brush.horizontalGradient(listOf(Color(0xff292e31),Color(0xff171b1e)))).border(1.dp,Color.White.copy(.11f),shape).clickable{set(!value)}.padding(horizontal=17.dp),verticalAlignment=Alignment.CenterVertically){Text(title,Modifier.weight(1f),color=Color(0xffffdda0),fontWeight=FontWeight.Black,fontSize=11.sp);Switch(value,set,colors=SwitchDefaults.colors(checkedThumbColor=Color(0xffffe1a5),checkedTrackColor=Color(0xff3c1d12),uncheckedThumbColor=Color(0xffc49a70),uncheckedTrackColor=Color(0xff62402c)))}
}
@Composable private fun DrawerNav(title:String,sub:String,go:()->Unit){Row(Modifier.fillMaxWidth().padding(vertical=6.dp).clip(RoundedCornerShape(12.dp)).background(Brush.horizontalGradient(listOf(Color(0xfffffbef),Color(0xffe2c99e)))).border(1.dp,Color(0xff9b6a3e).copy(.62f),RoundedCornerShape(12.dp)).clickable(onClick=go).padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,color=Color(0xff3f2116),fontWeight=FontWeight.Black,fontSize=12.sp);Text(sub,color=Color(0xff836247),fontSize=10.sp)};Text("›",color=Color(0xff7b492a),fontSize=25.sp)}}
@Composable private fun DrawerTab(icon:String,on:Boolean,go:()->Unit){FilledTonalButton(go,Modifier.size(58.dp),contentPadding=PaddingValues(0.dp),shape=RoundedCornerShape(18.dp),colors=ButtonDefaults.filledTonalButtonColors(containerColor=if(on)Color(0xffffd998)else Color(0xff3b1c11))){Text(icon,color=if(on)Color(0xff3b1c11)else Color(0xffffe2ad),fontSize=22.sp)}}
@Composable private fun DrawerButton(text:String,go:()->Unit){Button(go,Modifier.fillMaxWidth().padding(vertical=5.dp).height(50.dp),colors=ButtonDefaults.buttonColors(Color(0xfffff4de)),border=BorderStroke(1.dp,Color(0xffa87548))){Text(text,Modifier.fillMaxWidth(),color=Color(0xff3b2117),fontWeight=FontWeight.Bold)}}
@Composable private fun DrawerHeader(text:String){Text(text,Modifier.padding(top=18.dp,bottom=5.dp),color=Color(0xff615b50),fontSize=11.sp,fontWeight=FontWeight.Black,letterSpacing=2.sp)}
@Composable private fun DrawerSwitch(text:String,value:Boolean,set:(Boolean)->Unit){Row(Modifier.fillMaxWidth().padding(vertical=5.dp),verticalAlignment=Alignment.CenterVertically){Text(text,Modifier.weight(1f),color=Color(0xff3b2117),fontWeight=FontWeight.SemiBold);Switch(value,set,colors=SwitchDefaults.colors(checkedThumbColor=Color.White,checkedTrackColor=Color(0xff8b542f),uncheckedThumbColor=Color(0xff6f7475),uncheckedTrackColor=Color(0xffd7c19e)))}}
@Composable private fun DrawerChoice(text:String,on:Boolean=false,go:()->Unit){TextButton(go,Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp)).background(if(on)Color(0xffead0a4)else Color.Transparent)){Text((if(on)"◆  " else "")+text,Modifier.fillMaxWidth(),color=Color(0xff3b2117),fontWeight=if(on)FontWeight.Bold else FontWeight.Normal)}}
@Composable private fun ThemeChoice(theme:BoardTheme,on:Boolean,go:()->Unit){val p=boardPalette(theme);Row(Modifier.fillMaxWidth().padding(vertical=4.dp).clip(RoundedCornerShape(14.dp)).background(if(on)Color(0xffead0a4)else Color.Transparent).clickable(onClick=go).padding(9.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(48.dp,30.dp).clip(RoundedCornerShape(8.dp)).background(Brush.horizontalGradient(listOf(p.frame,p.field,p.pointA,p.pointB))).border(1.dp,Color(0xff9b6a3e),RoundedCornerShape(8.dp)));Spacer(Modifier.width(12.dp));Text(theme.fa(),Modifier.weight(1f),color=Color(0xff3b2117),fontWeight=if(on)FontWeight.Bold else FontWeight.Normal);if(on)Text("◆",color=Color(0xff665b49))}}
@Composable private fun MatchClocks(clock:ClockState,turn:Player,modifier:Modifier=Modifier){
 fun format(ms:Long):String{val safe=ms.coerceAtLeast(0);return if(safe<10_000)"${safe/1000}.${(safe%1000)/100}" else "%d:%02d".format(safe/60_000,(safe/1000)%60)}
 androidx.compose.runtime.CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Row(modifier,horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.Top){
  ClockFace("سفید",format(clock.whiteMillis),turn==Player.WHITE,clock.turnMillis)
  ClockFace("سیاه",format(clock.blackMillis),turn==Player.BLACK,clock.turnMillis)
 }}
}
@Composable private fun ClockFace(label:String,time:String,active:Boolean,turnMillis:Long){
 val shape=RoundedCornerShape(13.dp);val edge=if(active)Color(0xffffd58a)else Color.White.copy(.26f)
 Box(Modifier.width(126.dp).height(46.dp).graphicsLayer{shadowElevation=12.dp.toPx();this.shape=shape;clip=false}){
  Box(Modifier.align(Alignment.BottomCenter).fillMaxWidth(.90f).height(12.dp).clip(RoundedCornerShape(bottomStart=8.dp,bottomEnd=8.dp)).background(Brush.verticalGradient(listOf(Color(0xff9b633d),Color(0xff3a190f)))).border(.7.dp,Color(0xffd99b64).copy(.55f),RoundedCornerShape(bottomStart=8.dp,bottomEnd=8.dp)))
  Box(Modifier.fillMaxWidth().height(42.dp).clip(shape).background(Brush.linearGradient(if(active)listOf(Color(0xdde8e1d5),Color(0xb8a6b0ac),Color(0xd84d413a))else listOf(Color(0xcac7cbc8),Color(0x9d7c8583),Color(0xc637302e)))).border(if(active)1.5.dp else 1.dp,edge,shape).padding(horizontal=7.dp)){
   Box(Modifier.matchParentSize().padding(2.dp).clip(RoundedCornerShape(11.dp)).background(Brush.verticalGradient(listOf(Color.White.copy(.20f),Color.Transparent,Color.Black.copy(.14f)))))
   Text(label,Modifier.align(Alignment.TopEnd).padding(top=3.dp),color=if(active)Color(0xff422418)else Color.White.copy(.74f),fontSize=6.sp,fontWeight=FontWeight.Black,letterSpacing=1.2.sp)
   Text(time,Modifier.align(Alignment.Center).offset(y=2.dp),color=if(active)Color(0xff2a1711)else Color.White.copy(.88f),fontSize=16.sp,fontWeight=FontWeight.Black,letterSpacing=.7.sp)
   Box(Modifier.align(Alignment.CenterStart).size(25.dp).clip(androidx.compose.foundation.shape.CircleShape).background(Color(0xff241711).copy(.72f)).border(1.dp,edge.copy(.75f),androidx.compose.foundation.shape.CircleShape),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("نوبت",fontSize=5.sp,color=Color.White.copy(.56f),lineHeight=5.sp);Text("${(turnMillis/1000).coerceAtLeast(0)}",color=if(turnMillis<3000)Color(0xffff8075)else Color.White,fontSize=9.sp,fontWeight=FontWeight.Black,lineHeight=9.sp)}}
  }
 }
}
@Composable private fun CarvedScoreCounter(white:Int,black:Int,modifier:Modifier=Modifier){
 Box(modifier.size(204.dp,49.dp),contentAlignment=Alignment.TopCenter){
  Box(Modifier.align(Alignment.Center).width(174.dp).height(3.dp).background(Brush.verticalGradient(listOf(Color(0xffeee9e2),Color(0xff5a5651)))))
  // Wooden feet visibly join the mechanism to the board's upper rail.
  Box(Modifier.align(Alignment.BottomStart).padding(start=18.dp).size(17.dp,22.dp).clip(RoundedCornerShape(bottomStart=5.dp,bottomEnd=5.dp)).background(Brush.horizontalGradient(listOf(Color(0xff35180d),Color(0xff8d5634),Color(0xff35180d)))))
  Box(Modifier.align(Alignment.BottomEnd).padding(end=18.dp).size(17.dp,22.dp).clip(RoundedCornerShape(bottomStart=5.dp,bottomEnd=5.dp)).background(Brush.horizontalGradient(listOf(Color(0xff35180d),Color(0xff8d5634),Color(0xff35180d)))))
  Row(Modifier.height(43.dp).graphicsLayer{shadowElevation=7.dp.toPx();shape=RoundedCornerShape(7.dp);clip=false}.clip(RoundedCornerShape(7.dp)).background(Brush.verticalGradient(listOf(Color(0xff9b613b),Color(0xff35180d)))).border(1.dp,Color(0xffdda66f).copy(.65f),RoundedCornerShape(7.dp)).padding(horizontal=8.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(3.dp)){
   repeat(3){Box(Modifier.size(14.dp).clip(androidx.compose.foundation.shape.CircleShape).background(Brush.radialGradient(listOf(Color(0xff77706d),Color(0xff090909)))).border(.5.dp,Color.White.copy(.26f),androidx.compose.foundation.shape.CircleShape))}
   Box(Modifier.height(35.dp).clip(RoundedCornerShape(5.dp)).background(Brush.verticalGradient(listOf(Color(0xffc7c2bb),Color(0xff4f4c49)))).border(1.dp,Color(0xffeee8df),RoundedCornerShape(5.dp)).padding(horizontal=5.dp),contentAlignment=Alignment.Center){Row(horizontalArrangement=Arrangement.spacedBy(3.dp)){ScoreDrum(black);ScoreDrum(white)}}
   repeat(3){Box(Modifier.size(14.dp).clip(androidx.compose.foundation.shape.CircleShape).background(Brush.radialGradient(listOf(Color.White,Color(0xffd8d0c8),Color(0xff88827e)))).border(.5.dp,Color.Black.copy(.22f),androidx.compose.foundation.shape.CircleShape))}
  }
 }
}
@Composable private fun ScoreDrum(score:Int){Box(Modifier.size(26.dp,29.dp).clip(RoundedCornerShape(3.dp)).background(Brush.verticalGradient(listOf(Color(0xff080808),Color(0xff242424),Color.Black))).border(.5.dp,Color.White.copy(.28f),RoundedCornerShape(3.dp)),contentAlignment=Alignment.Center){Text((score%10).toString(),color=Color.White,fontSize=17.sp,fontWeight=FontWeight.Medium)}}
@Composable private fun ClockSettingsButton(go:()->Unit,modifier:Modifier=Modifier){val shape=RoundedCornerShape(9.dp);Box(modifier.size(32.dp,28.dp).clip(shape).background(Brush.verticalGradient(listOf(Color(0xff94603e),Color(0xff3b1b11)))).border(1.dp,Color(0xffffce88).copy(.58f),shape).clickable(onClick=go),contentAlignment=Alignment.Center){Text("⚙",color=Color(0xffffe0aa),fontSize=15.sp)}}
@Composable private fun TopGameBar(level:Difficulty,clockOn:Boolean,status:String,settings:()->Unit,modifier:Modifier=Modifier){CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Row(modifier.fillMaxWidth().height(30.dp).background(Brush.verticalGradient(listOf(Color(0xff75442d),Color(0xff4b2618)))).border(BorderStroke(1.dp,Brush.verticalGradient(listOf(Color(0xffd7a06e).copy(.55f),Color(0xff241008).copy(.65f))))).padding(horizontal=if(clockOn)18.dp else 10.dp),verticalAlignment=Alignment.CenterVertically){IconButton(settings,Modifier.size(28.dp)){Text("⚙",color=Color(0xffffdfa0),fontSize=16.sp)};if(!clockOn)Text("هوش مصنوعی • ${level.fa()} • سطح ${level.ordinal+1}",Modifier.padding(start=8.dp),color=Color.White.copy(.76f),fontSize=9.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text(if(clockOn)status.replace("YOUR ","") else status,color=Color(0xffffd77a),fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=.6.sp)}}}
@Composable private fun MiniWoodButton(text:String,modifier:Modifier=Modifier,go:()->Unit){Button(go,modifier.height(38.dp),contentPadding=PaddingValues(horizontal=10.dp),shape=RoundedCornerShape(9.dp),colors=ButtonDefaults.buttonColors(containerColor=Color(0xff5a2b1a),contentColor=Color(0xffffe0a0)),border=BorderStroke(1.dp,Color(0xffd59a63))){Text(text,fontSize=11.sp,fontWeight=FontWeight.Black)}}
@Composable private fun SceneArrow(text:String,modifier:Modifier=Modifier,go:()->Unit){Box(modifier.size(38.dp,72.dp).clip(RoundedCornerShape(18.dp)).background(Color(0xff17110e).copy(.64f)).border(1.dp,Color.White.copy(.38f),RoundedCornerShape(18.dp)).clickable(onClick=go),contentAlignment=Alignment.Center){Text(text,color=Color.White,fontSize=34.sp,fontWeight=FontWeight.Light)}}
@Composable private fun BarEngraving(text:String,modifier:Modifier=Modifier,go:()->Unit){
 val shape=RoundedCornerShape(4.dp)
 Box(modifier.width(72.dp).height(29.dp).graphicsLayer{shadowElevation=7.dp.toPx();this.shape=shape;clip=false}.clip(shape).background(Brush.verticalGradient(listOf(Color(0xff1e0d07).copy(.72f),Color(0xff5b301d).copy(.66f),Color(0xff9a623a).copy(.28f)))).border(1.5.dp,Color(0xff1b0b06).copy(.88f),shape).clickable(onClick=go),contentAlignment=Alignment.Center){
  Box(Modifier.fillMaxWidth().height(1.dp).align(Alignment.TopCenter).background(Color.Black.copy(.45f)));Box(Modifier.fillMaxWidth().height(1.dp).align(Alignment.BottomCenter).background(Color(0xffd7a16d).copy(.24f)))
  Text(text,Modifier.offset(y=1.dp),color=Color(0xffffd49a).copy(.28f),fontSize=10.sp,fontWeight=FontWeight.Black,letterSpacing=1.4.sp);Text(text,Modifier.offset(y=(-.5).dp),color=Color(0xff1c0d08),fontSize=10.sp,fontWeight=FontWeight.Black,letterSpacing=1.4.sp)
 }
}
@Composable private fun AxleDoublingCube(value:Int,owner:Player?,pending:Player?,enabled:Boolean,go:()->Unit,modifier:Modifier=Modifier){
 val pulse by rememberInfiniteTransition(label="cubeOffer").animateFloat(.52f,1f,infiniteRepeatable(tween(850),RepeatMode.Reverse),label="cubePulse");val rotation=remember{Animatable(0f)};var lastValue by remember{mutableIntStateOf(value)};var accepted by remember{mutableStateOf(false)}
 LaunchedEffect(value,pending){val changed=value!=lastValue;if(changed){accepted=true;lastValue=value};rotation.snapTo(0f);rotation.animateTo(360f,tween(720,easing=FastOutSlowInEasing));if(changed){delay(1350);accepted=false}}
 val shown=if(value<=1)2 else if(owner!=null)(value*2).coerceAtMost(64)else value;val octagon=androidx.compose.foundation.shape.GenericShape{size,_->val cut=size.minDimension*.22f;moveTo(cut,0f);lineTo(size.width-cut,0f);lineTo(size.width,cut);lineTo(size.width,size.height-cut);lineTo(size.width-cut,size.height);lineTo(cut,size.height);lineTo(0f,size.height-cut);lineTo(0f,cut);close()};val glow=when{accepted->Color(0xff63df78);pending!=null->Color(0xffffc85e);enabled->Color(0xffffd36f);else->Color(0xff735039)};val glowAlpha=if(enabled||pending!=null||accepted){.72f+.25f*pulse}else .55f
 Box(modifier.size(112.dp,38.dp).clickable(enabled=enabled,onClick=go),contentAlignment=Alignment.Center){
  Canvas(Modifier.fillMaxWidth().height(16.dp)){val y=size.height/2;drawLine(Color.Black.copy(.42f),Offset(7f,y+2f),Offset(size.width-7f,y+2f),6f,cap=StrokeCap.Round);drawLine(Brush.horizontalGradient(listOf(Color(0xff4b2517),Color(0xffd7a05f),Color(0xff4b2517))),Offset(7f,y),Offset(size.width-7f,y),4.2f,cap=StrokeCap.Round);drawCircle(Color(0xffefb86f),3.5f,Offset(8f,y));drawCircle(Color(0xffefb86f),3.5f,Offset(size.width-8f,y))}
  Box(Modifier.size(36.dp).graphicsLayer{rotationY=rotation.value;cameraDistance=10f*density;shadowElevation=8.dp.toPx();shape=octagon;clip=false}.clip(octagon).background(Brush.linearGradient(listOf(Color(0xfffff0c7),Color(0xffd1a963),Color(0xff76502f)))).border(if(enabled||pending!=null||accepted)2.dp else 1.dp,glow.copy(glowAlpha),octagon),contentAlignment=Alignment.Center){Canvas(Modifier.fillMaxSize()){val c=Offset(size.width/2,size.height/2);for(i in 0 until 8){val a=Math.toRadians((i*45.0-90));val b=Math.toRadians((i*45.0-67.5));val p1=Offset(c.x+cos(a).toFloat()*size.width*.46f,c.y+sin(a).toFloat()*size.height*.46f);val p2=Offset(c.x+cos(b).toFloat()*size.width*.35f,c.y+sin(b).toFloat()*size.height*.35f);drawLine(Color(0xff5d3822).copy(.28f),p1,p2,1f)}};Text("${shown}x",color=if(accepted)Color(0xff176b2d)else Color(0xff342015),fontSize=12.sp,fontWeight=FontWeight.Black,style=androidx.compose.ui.text.TextStyle(shadow=androidx.compose.ui.graphics.Shadow(Color.White.copy(.42f),Offset(-1f,-1f),1f)))}
 }
}
@Composable private fun EngravedWoodAction(text:String,modifier:Modifier=Modifier,go:()->Unit){val shape=RoundedCornerShape(7.dp);Box(modifier.width(78.dp).height(29.dp).clip(shape).background(Brush.verticalGradient(listOf(Color.Black.copy(.28f),Color(0xff6a3b25).copy(.72f),Color.White.copy(.08f)))).border(1.dp,Color(0xff2b140c).copy(.72f),shape).clickable(onClick=go),contentAlignment=Alignment.Center){Box(Modifier.fillMaxWidth().height(1.dp).align(Alignment.TopCenter).background(Color.Black.copy(.48f)));Text(text,Modifier.offset(y=1.dp),color=Color.White.copy(.13f),fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=.8.sp);Text(text,Modifier.offset(y=(-.4).dp),color=Color(0xff251109),fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=.8.sp)}}
@Composable private fun InlayButton(text:String,modifier:Modifier=Modifier,go:()->Unit){Button(go,modifier.widthIn(min=68.dp).height(30.dp),contentPadding=PaddingValues(horizontal=10.dp),shape=RoundedCornerShape(8.dp),colors=ButtonDefaults.buttonColors(containerColor=Color(0xff55301f),contentColor=Color(0xffffdfa0)),border=BorderStroke(1.dp,Color(0xffbb8254))){Text(text,fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=.5.sp)}}
@Composable private fun PlayerCard(name:String,score:Int,active:Boolean,light:Boolean){Row(Modifier.clip(RoundedCornerShape(18.dp)).background(if(active)Glass else Glass.copy(.58f)).border(if(active)1.dp else 0.dp,if(active)Gold else Color.Transparent,RoundedCornerShape(18.dp)).padding(horizontal=14.dp,vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(32.dp).clip(androidx.compose.foundation.shape.CircleShape).background(if(light)Color(0xffffe7bd)else Color(0xff1d2028)));Spacer(Modifier.width(9.dp));Column{Text(name,fontSize=11.sp,fontWeight=FontWeight.Bold,color=Color.White);Row(Modifier.padding(top=5.dp),horizontalArrangement=Arrangement.spacedBy(3.dp)){repeat(5){i->Box(Modifier.size(6.dp).clip(androidx.compose.foundation.shape.CircleShape).background(if(i<score.coerceAtMost(5))Gold else Color.White.copy(.20f)))}}}}}
@Composable private fun StatusPill(t:String){Text(t,Modifier.clip(RoundedCornerShape(50)).background(Glass).border(1.dp,Color.White.copy(.12f),RoundedCornerShape(50)).padding(horizontal=20.dp,vertical=9.dp),fontSize=11.sp,fontWeight=FontWeight.Bold,letterSpacing=1.sp,color=Color.White)}
@Composable private fun AnimatedDice(finalDice:List<Int>,style:DiceStyle,rolling:Boolean,onThrow:()->Unit,modifier:Modifier=Modifier){
 var drag by remember{mutableStateOf(Offset.Zero)};var throwVector by remember{mutableStateOf(Offset.Zero)}
 val x1=remember{Animatable(-90f)};val y1=remember{Animatable(-45f)};val r1=remember{Animatable(0f)}
 val x2=remember{Animatable(90f)};val y2=remember{Animatable(-35f)};val r2=remember{Animatable(0f)}
 var face1 by remember{mutableIntStateOf(1)};var face2 by remember{mutableIntStateOf(6)}
 LaunchedEffect(rolling){
  if(rolling){
   val released=throwVector;x1.snapTo(x1.value+released.x);x2.snapTo(x2.value+released.x);y1.snapTo(y1.value+released.y);y2.snapTo(y2.value+released.y);drag=Offset.Zero
   val tx1=(-82..-64).random().toFloat();val tx2=(64..82).random().toFloat();val commonY=(released.y*.12f).coerceIn(-18f,18f);val ty1=commonY+(-7..7).random();val ty2=commonY+(-7..7).random()
   kotlinx.coroutines.coroutineScope{
    launch{x1.animateTo(tx1,tween(1650,easing=FastOutSlowInEasing))};launch{x2.animateTo(tx2,tween(1680,easing=FastOutSlowInEasing))}
    launch{y1.animateTo(ty1,keyframes{durationMillis=1680;y1.value at 0;(ty1-42f) at 420;(ty1+10f) at 930;ty1 at 1680})}
    launch{y2.animateTo(ty2,keyframes{durationMillis=1680;y2.value at 0;(ty2-38f) at 460;(ty2+8f) at 970;ty2 at 1680})}
    launch{r1.animateTo(r1.value+720f,tween(1680,easing=LinearOutSlowInEasing))};launch{r2.animateTo(r2.value-720f,tween(1680,easing=LinearOutSlowInEasing))}
   }
  } else {face1=finalDice.getOrElse(0){face1};face2=finalDice.getOrElse(1){face2};r1.snapTo(0f);r2.snapTo(0f);drag=Offset.Zero}
 }
 Box(modifier.size(230.dp,140.dp).graphicsLayer{translationX=drag.x;translationY=drag.y}.then(if(!rolling&&finalDice.isEmpty())Modifier.pointerInput(Unit){detectDragGestures(onDragEnd={if(drag.getDistance()>24f){throwVector=drag;onThrow()}else drag=Offset.Zero},onDragCancel={drag=Offset.Zero}){change,amount->change.consume();drag+=amount}}else Modifier)){DieFace(finalDice.getOrElse(0){face1},style,rolling,Modifier.align(Alignment.Center).offset{x1.value.roundToInt().let{androidx.compose.ui.unit.IntOffset(it,y1.value.roundToInt())}}.rotate(r1.value));DieFace(finalDice.getOrElse(1){face2},style,rolling,Modifier.align(Alignment.Center).offset{x2.value.roundToInt().let{androidx.compose.ui.unit.IntOffset(it,y2.value.roundToInt())}}.rotate(r2.value));if(!rolling&&finalDice.size>2)DieFace(finalDice[2],style,false,Modifier.align(Alignment.Center).offset(x=(-34).dp,y=48.dp));if(!rolling&&finalDice.size>3)DieFace(finalDice[3],style,false,Modifier.align(Alignment.Center).offset(x=34.dp,y=48.dp))}
}
@Composable private fun DieFace(value:Int,style:DiceStyle,rolling:Boolean,modifier:Modifier=Modifier){
 val base=when(style){DiceStyle.CLASSIC->Color(0xffffedc5);DiceStyle.ONYX->Color(0xff252731);DiceStyle.CRYSTAL, DiceStyle.GLASS_LIGHT->Color(0xff77dce6);DiceStyle.GLASS_DARK->Color(0xff123b52);DiceStyle.GOLD->Color(0xffd99a3d);DiceStyle.SILVER->Color(0xffc8cbcd);DiceStyle.MARBLE_LIGHT->Color(0xffe9e7df);DiceStyle.MARBLE_DARK->Color(0xff303538);DiceStyle.BURGUNDY->Color(0xff70232d);DiceStyle.JADE->Color(0xff83ae91);DiceStyle.SAPPHIRE->Color(0xff123c91)};val lightInk=style in listOf(DiceStyle.CLASSIC,DiceStyle.GOLD,DiceStyle.SILVER,DiceStyle.MARBLE_LIGHT,DiceStyle.GLASS_LIGHT);val ink=if(lightInk)Color(0xff28231f)else Color.White;val rim=when(style){DiceStyle.GOLD->Color(0xffffd27c);DiceStyle.SILVER->Color(0xfff5f6f5);DiceStyle.MARBLE_LIGHT,DiceStyle.MARBLE_DARK->Color(0xff89959b);DiceStyle.CRYSTAL,DiceStyle.GLASS_LIGHT,DiceStyle.GLASS_DARK->Color(0xff9beef3);else->Color(0xff765a40)}
 Canvas(modifier.size(46.dp)){
  val u=size.minDimension/62f
  drawRoundRect(Color.Black.copy(.34f),Offset(9*u,11*u),Size(46*u,47*u),CornerRadius(14*u))
  drawRoundRect(rim.copy(.44f),Offset(6*u,6*u),Size(46*u,46*u),CornerRadius(13*u),style=Stroke(2.4f*u))
  drawRoundRect(base.copy(.58f),Offset(7*u,10*u),Size(44*u,45*u),CornerRadius(12*u));drawLine(Color.Black.copy(.24f),Offset(12*u,54*u),Offset(46*u,54*u),2.2f*u)
  drawRoundRect(Brush.linearGradient(listOf(Color.White.copy(.58f),base,base.copy(.74f))),Offset(7*u,5*u),Size(44*u,44*u),CornerRadius(12*u));drawRoundRect(rim.copy(.72f),Offset(7*u,5*u),Size(44*u,44*u),CornerRadius(12*u),style=Stroke(1.5f*u));drawRoundRect(Color.White.copy(.54f),Offset(9*u,7*u),Size(40*u,40*u),CornerRadius(10*u),style=Stroke(1.2f*u))
  when(style){DiceStyle.GOLD,DiceStyle.SILVER->{repeat(7){i->drawLine((if(i%2==0)Color.White else Color.Black).copy(.10f),Offset(11*u,(11+i*5)*u),Offset(47*u,(11+i*5)*u),.6f*u)}};DiceStyle.MARBLE_LIGHT,DiceStyle.MARBLE_DARK->{val vein=Path().apply{moveTo(10*u,18*u);cubicTo(21*u,12*u,29*u,34*u,48*u,27*u);cubicTo(39*u,38*u,31*u,39*u,18*u,47*u)};drawPath(vein,rim.copy(.22f),style=Stroke(1.1f*u))};DiceStyle.CRYSTAL,DiceStyle.GLASS_LIGHT,DiceStyle.GLASS_DARK->drawRoundRect(Brush.radialGradient(listOf(Color.White.copy(.28f),Color.Transparent),Offset(17*u,14*u),28*u),Offset(9*u,7*u),Size(40*u,40*u),CornerRadius(10*u));else->Unit}
  val spots=when(value){1->listOf(.5f to .5f);2->listOf(.28f to .28f,.72f to .72f);3->listOf(.27f to .27f,.5f to .5f,.73f to .73f);4->listOf(.28f to .28f,.72f to .28f,.28f to .72f,.72f to .72f);5->listOf(.27f to .27f,.73f to .27f,.5f to .5f,.27f to .73f,.73f to .73f);else->listOf(.28f to .23f,.72f to .23f,.28f to .5f,.72f to .5f,.28f to .77f,.72f to .77f)}
  spots.forEach{drawCircle(Color.Black.copy(.42f),4.2f*u,Offset((7+44*it.first)*u,(7+44*it.second)*u));drawCircle(ink,3.55f*u,Offset((7+44*it.first)*u,(7+44*it.second)*u));drawCircle(Color.White.copy(.22f),.9f*u,Offset((6.2f+44*it.first)*u,(6.2f+44*it.second)*u))};listOf(15f to 20f,42f to 18f,25f to 48f,45f to 40f).forEach{drawCircle(Color(0xff8e7253).copy(.10f),.7f*u,Offset(it.first*u,it.second*u))}
 }
}
@Composable private fun RoundAction(t:String,go:()->Unit){FilledTonalButton(go,contentPadding=PaddingValues(0.dp),modifier=Modifier.size(46.dp),shape=androidx.compose.foundation.shape.CircleShape){Text(t,fontWeight=FontWeight.Bold)}}
