package com.arena.backgammon.ui

import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.*
import androidx.compose.ui.res.imageResource
import androidx.compose.ui.input.pointer.pointerInput
import com.arena.backgammon.R
import com.arena.backgammon.core.*
import com.arena.backgammon.data.*
import kotlin.math.*

private data class CheckerMotion(val from:Int,val to:Int,val white:Boolean)
data class BoardPalette(val frame:Color,val frameDark:Color,val field:Color,val pointA:Color,val pointB:Color,val light:Color,val dark:Color,val accent:Color)
fun boardPalette(t:BoardTheme)=when(t){
 BoardTheme.PREMIUM_WOOD->BoardPalette(Color(0xff925d39),Color(0xff3a1c10),Color(0xffbd8a61),Color(0xffd8bd8d),Color(0xff6d2730),Color(0xffffdfa0),Color(0xff351a15),Color(0xffd7b25b))
 BoardTheme.MARBLE_STONE->BoardPalette(Color(0xff8c9298),Color(0xff30363c),Color(0xffc8c9c5),Color(0xfff0eee7),Color(0xff596773),Color(0xfff5f3ea),Color(0xff263039),Color(0xffb9c5cc))
 BoardTheme.SMOKED_GLASS->BoardPalette(Color(0xff334650),Color(0xff0b151b),Color(0xff183541),Color(0xff9ed4db),Color(0xff245f70),Color(0xffd5f5f4),Color(0xff0b2029),Color(0xff7de3e8))
}

/** Precise top-down board inspired by classic mobile layouts, drawn entirely with original vector assets. */
@Composable fun FlatBoard(state:TurnState,theme:BoardTheme,pieces:PieceStyle,selected:Int?,legal:List<Move>,select:(Int)->Unit,move:(Move)->Unit,combine:(Int,Int)->Boolean={_,_->false},modifier:Modifier=Modifier){
 val p=boardPalette(theme);val texture=ImageBitmap.imageResource(when(theme){BoardTheme.PREMIUM_WOOD->R.drawable.premium_walnut_texture;BoardTheme.MARBLE_STONE->R.drawable.ivory_marble_texture;BoardTheme.SMOKED_GLASS->R.drawable.smoked_glass_texture});val materialBrush=remember(texture){ShaderBrush(ImageShader(texture,TileMode.Mirror,TileMode.Mirror))};val pulse by rememberInfiniteTransition(label="legal").animateFloat(.58f,1f,infiniteRepeatable(tween(650),RepeatMode.Reverse),label="pulse")
 var previous by remember{mutableStateOf(state.position.copyDeep())};var motion by remember{mutableStateOf<CheckerMotion?>(null)};val travel=remember{Animatable(1f)}
 LaunchedEffect(state.position){
  val now=state.position;val mover=previous.turn;val sign=mover.sign
  if(!previous.points.contentEquals(now.points)||previous.bar(mover)!=now.bar(mover)||previous.off(mover)!=now.off(mover)){
   val from=(0..23).firstOrNull{previous.points[it]*sign>now.points[it]*sign}?:if(previous.bar(mover)>now.bar(mover))Move.BAR else null
   val to=(0..23).firstOrNull{now.points[it]*sign>previous.points[it]*sign}?:if(now.off(mover)>previous.off(mover))Move.OFF else null
   if(from!=null&&to!=null){motion=CheckerMotion(from,to,mover==Player.WHITE);travel.snapTo(0f);travel.animateTo(1f,tween(1080,easing=FastOutSlowInEasing));motion=null}
  }
  previous=now.copyDeep()
 }
 Canvas(modifier.pointerInput(state,selected){detectTapGestures{tap->
  val rail=size.width*.032f;val barW=size.width*.083f;val playLeft=rail;val playRight=size.width-size.width*.060f;val half=(playRight-playLeft-barW)/2;val barLeft=playLeft+half
  val bar=tap.x in (barLeft-barW*.28f)..(barLeft+barW*1.28f);val off=tap.x>playRight;val local=if(tap.x<barLeft)tap.x-playLeft else tap.x-(barLeft+barW)+half
  val col=(local/(half/6)).toInt().coerceIn(0,11);val point=if(tap.y<size.height/2)12+col else 11-col;val target=when{off->Move.OFF;bar->Move.BAR;else->point};val choices=legal.filter{it.from==selected&&it.to==target};if(choices.isNotEmpty())move(choices.maxBy{it.die})else if(selected!=null&&target!=Move.BAR&&combine(selected,target))Unit else {val owns=target==Move.BAR&&state.position.bar(state.position.turn)>0||target in 0..23&&state.position.points[target]*state.position.turn.sign>0;if(owns)select(target)}
 }}){
  val rail=size.width*.032f;val barW=size.width*.083f;val playLeft=rail;val playRight=size.width-size.width*.060f;val half=(playRight-playLeft-barW)/2;val barLeft=playLeft+half;val cw=half/6
  drawRoundRect(materialBrush,cornerRadius=CornerRadius(18f));drawRoundRect(Brush.verticalGradient(listOf(Color.White.copy(.18f),p.frame.copy(.16f),p.frameDark.copy(.30f))),cornerRadius=CornerRadius(18f));drawRoundRect(Color.Black.copy(.38f),Offset(rail*.42f,rail*.32f),Size(size.width-rail*1.18f,size.height-rail*.64f),CornerRadius(12f));drawRect(materialBrush,Offset(playLeft,rail),Size(playRight-playLeft,size.height-rail*2));drawRect(p.field.copy(if(theme==BoardTheme.SMOKED_GLASS).55f else .16f),Offset(playLeft,rail),Size(playRight-playLeft,size.height-rail*2));drawRect(p.frameDark.copy(.36f),Offset(playLeft,rail),Size(playRight-playLeft,size.height-rail*2),style=Stroke(12f));drawLine(Color.White.copy(.20f),Offset(playLeft+6f,rail+6f),Offset(playRight-6f,rail+6f),2.5f);drawLine(Color.White.copy(.12f),Offset(playLeft+6f,rail+6f),Offset(playLeft+6f,size.height-rail-6f),2f);drawRect(Brush.verticalGradient(listOf(p.frameDark.copy(.52f),p.frame.copy(.22f),Color.Transparent)),Offset(playLeft,rail),Size(playRight-playLeft,18f));drawRect(Brush.verticalGradient(listOf(Color.Transparent,p.frame.copy(.18f),p.frameDark.copy(.48f))),Offset(playLeft,size.height-rail-18f),Size(playRight-playLeft,18f));drawRect(Brush.horizontalGradient(listOf(p.frameDark.copy(.46f),p.frame.copy(.18f),Color.Transparent)),Offset(playLeft,rail),Size(17f,size.height-rail*2));drawRect(Brush.horizontalGradient(listOf(Color.Transparent,p.frame.copy(.15f),p.frameDark.copy(.42f))),Offset(playRight-15f,rail),Size(15f,size.height-rail*2));drawRect(Color.Black.copy(.62f),Offset(barLeft+11f,rail+10f),Size(barW,size.height-rail*2));drawRect(materialBrush,Offset(barLeft,rail),Size(barW,size.height-rail*2));drawRect(Brush.horizontalGradient(listOf(p.frame.copy(.82f),p.frame.copy(.30f),p.frameDark.copy(.74f))),Offset(barLeft,rail),Size(barW,size.height-rail*2));drawLine(Color.White.copy(.32f),Offset(barLeft+3f,rail),Offset(barLeft+3f,size.height-rail),4f);drawLine(Color.Black.copy(.66f),Offset(barLeft+barW-5f,rail),Offset(barLeft+barW-5f,size.height-rail),10f);drawRect(Brush.horizontalGradient(listOf(p.frame.copy(.74f),p.field.copy(.76f),p.frame.copy(.62f))),Offset(playRight,rail),Size(size.width-playRight-rail*.25f,size.height-rail*2))
  // Layered bevels and deterministic grain give the frame and playing bed physical depth.
  drawRoundRect(Color.White.copy(.24f),Offset(4f,4f),Size(size.width-8f,size.height-8f),CornerRadius(13f),style=Stroke(4f));drawRoundRect(p.frameDark.copy(.46f),Offset(rail*.28f,rail*.28f),Size(size.width-rail*.85f,size.height-rail*.56f),CornerRadius(7f),style=Stroke(8f))
  when(theme){
   BoardTheme.PREMIUM_WOOD->for(i in 0..22){val y=rail+(size.height-rail*2)*i/22f;val grain=Path().apply{moveTo(playLeft,y);cubicTo(size.width*.28f,y+sin(i*1.7f)*6f,size.width*.62f,y+cos(i*1.3f)*5f,playRight,y)};drawPath(grain,Color(0xff4b2415).copy(if(i%4==0).15f else .065f),style=Stroke(if(i%4==0)1.6f else .8f))}
   BoardTheme.MARBLE_STONE->for(i in 0..9){val x=playLeft+(playRight-playLeft)*i/9f;val vein=Path().apply{moveTo(x,rail);cubicTo(x+sin(i*2f)*38f,size.height*.30f,x+cos(i*1.3f)*55f,size.height*.68f,x+sin(i*.7f)*30f,size.height-rail)};drawPath(vein,Color.White.copy(if(i%3==0).24f else .11f),style=Stroke(if(i%3==0)2.8f else 1.2f));drawPath(vein,Color(0xff505860).copy(.08f),style=Stroke(4.5f))}
   BoardTheme.SMOKED_GLASS->{drawRect(Brush.linearGradient(listOf(Color.White.copy(.16f),Color.Transparent,Color(0xff6de7ef).copy(.10f))),Offset(playLeft,rail),Size(playRight-playLeft,size.height-rail*2));for(i in 0..7)drawLine(Color.White.copy(.07f),Offset(playLeft+i*90f,rail),Offset(playLeft+i*90f+180f,size.height-rail),1.4f)}
  }
  for(i in 0..7){val y=(i+.5f)*size.height/8f;drawLine(Color.Black.copy(.10f),Offset(3f,y),Offset(rail*.9f,y+sin(i.toFloat())*6f),1.2f);drawLine(Color.White.copy(.07f),Offset(playRight,y),Offset(size.width-4f,y+cos(i.toFloat())*5f),1f)}
  val trayX=playRight+size.width*.006f;val trayW=size.width-playRight-size.width*.012f;val trayH=size.height*.40f
  drawRoundRect(Brush.horizontalGradient(listOf(p.frameDark.copy(.54f),p.frame.copy(.68f),p.frameDark.copy(.54f))),Offset(trayX,rail*2.2f),Size(trayW,trayH),CornerRadius(10f));drawRoundRect(p.frameDark.copy(.28f),Offset(trayX,rail*2.2f),Size(trayW,trayH),CornerRadius(10f),style=Stroke(3.5f));drawRoundRect(Color.White.copy(.18f),Offset(trayX+4f,rail*2.2f+4f),Size(trayW-8f,trayH-8f),CornerRadius(8f),style=Stroke(2f));drawRoundRect(Brush.horizontalGradient(listOf(p.frameDark.copy(.54f),p.frame.copy(.68f),p.frameDark.copy(.54f))),Offset(trayX,size.height-rail*2.2f-trayH),Size(trayW,trayH),CornerRadius(10f));drawRoundRect(p.frameDark.copy(.28f),Offset(trayX,size.height-rail*2.2f-trayH),Size(trayW,trayH),CornerRadius(10f),style=Stroke(3.5f));drawRoundRect(Color.White.copy(.18f),Offset(trayX+4f,size.height-rail*2.2f-trayH+4f),Size(trayW-8f,trayH-8f),CornerRadius(8f),style=Stroke(2f))
  fun DrawScope.carvedSlot(y:Float){val sx=trayX+trayW*.16f;val sw=trayW*.68f;val sh=(trayH-16f)/15f*.62f;drawRoundRect(Color.Black.copy(.42f),Offset(sx-1.5f,y-1.5f),Size(sw+3f,sh+3f),CornerRadius(sh/2));drawRoundRect(Brush.verticalGradient(listOf(p.frameDark.copy(.58f),p.frame.copy(.34f))),Offset(sx,y),Size(sw,sh),CornerRadius(sh/2));drawLine(Color.White.copy(.23f),Offset(sx+sh*.35f,y+sh-1f),Offset(sx+sw-sh*.35f,y+sh-1f),1f)};val slotStep=(trayH-16f)/15f;for(i in 0..14){carvedSlot(rail*2.2f+8f+i*slotStep);carvedSlot(size.height-rail*2.2f-trayH+8f+i*slotStep)}
  val trayMark=Path().apply{moveTo(trayX+trayW/2,size.height*.47f);lineTo(trayX+trayW*.72f,size.height/2);lineTo(trayX+trayW/2,size.height*.53f);lineTo(trayX+trayW*.28f,size.height/2);close()};drawPath(trayMark,p.accent.copy(.52f));drawPath(trayMark,Color.White.copy(.24f),style=Stroke(1.5f));drawLine(Color.White.copy(.18f),Offset(trayX+trayW*.18f,rail*2.2f+8f),Offset(trayX+trayW*.18f,rail*2.2f+trayH-8f),1.5f);drawLine(Color.White.copy(.18f),Offset(trayX+trayW*.18f,size.height-rail*2.2f-trayH+8f),Offset(trayX+trayW*.18f,size.height-rail*2.2f-8f),1.5f)
  drawLine(Color.Black.copy(.48f),Offset(playLeft,rail),Offset(playRight,rail),8f);drawLine(Color.White.copy(.18f),Offset(playLeft,rail+5f),Offset(playRight,rail+5f),2f);drawLine(Color.Black.copy(.42f),Offset(playLeft,size.height-rail),Offset(playRight,size.height-rail),8f);drawLine(Color.White.copy(.12f),Offset(playLeft,size.height-rail-5f),Offset(playRight,size.height-rail-5f),2f);drawLine(Color.Black.copy(.40f),Offset(playLeft,rail),Offset(playLeft,size.height-rail),7f);drawLine(Color.White.copy(.14f),Offset(playLeft+5f,rail),Offset(playLeft+5f,size.height-rail),2f)
  drawLine(Color.White.copy(.28f),Offset(barLeft+3f,rail),Offset(barLeft+3f,size.height-rail),3f);drawLine(Color.Black.copy(.62f),Offset(barLeft+barW-3f,rail),Offset(barLeft+barW-3f,size.height-rail),6f);drawRoundRect(p.accent.copy(.46f),Offset(barLeft+6f,rail+6f),Size(barW-14f,size.height-rail*2-12f),CornerRadius(7f),style=Stroke(2f));drawLine(Color.Black.copy(.24f),Offset(barLeft+barW*.50f,rail+9f),Offset(barLeft+barW*.50f,size.height-rail-9f),1.5f)
  for(c in 0..11){val x=if(c<6)playLeft+c*cw else barLeft+barW+(c-6)*cw;val color=if(c%2==0)p.pointA else p.pointB;val other=if(c%2==0)p.pointB else p.pointA;val top=Path().apply{moveTo(x+cw*.10f,rail);lineTo(x+cw*.90f,rail);lineTo(x+cw/2,size.height*.405f);close()};val bottom=Path().apply{moveTo(x+cw*.10f,size.height-rail);lineTo(x+cw*.90f,size.height-rail);lineTo(x+cw/2,size.height*.595f);close()};drawPath(top,Brush.verticalGradient(listOf(color.copy(.72f),color,color.copy(.76f)),rail,size.height*.43f));drawPath(bottom,Brush.verticalGradient(listOf(other.copy(.76f),other,other.copy(.72f)),size.height*.57f,size.height-rail));drawPath(top,Color.Black.copy(.20f),style=Stroke(1.5f));drawPath(bottom,Color.Black.copy(.20f),style=Stroke(1.5f))}
  fun center(point:Int,index:Int):Offset{val col=if(point<12)11-point else point-12;val x=if(col<6)playLeft+(col+.5f)*cw else barLeft+barW+(col-5.5f)*cw;val r=cw*.262f;val gap=min(r*1.72f,(size.height*.37f)/5);return Offset(x,if(point>=12)rail+r+index.coerceAtMost(4)*gap else size.height-rail-r-index.coerceAtMost(4)*gap)}
  fun DrawScope.piece(c:Offset,r:Float,white:Boolean,on:Boolean=false,available:Boolean=false){
   val base=when(theme){BoardTheme.PREMIUM_WOOD->if(white)Color(0xffe2c58d)else Color(0xff603326);BoardTheme.MARBLE_STONE->if(white)Color(0xffe8e8e2)else Color(0xff34434d);BoardTheme.SMOKED_GLASS->if(white)Color(0xffb5edf0)else Color(0xff123b52)}
   val edge=if(white)base.copy(.78f)else Color(0xff170d0c)
   drawOval(Color.Black.copy(.46f),Offset(c.x-r*.98f,c.y-r*.54f),Size(r*1.96f,r*1.94f))
   drawOval(edge.copy(.78f),Offset(c.x-r,c.y-r*.78f),Size(r*2f,r*2.02f))
   drawOval(Color.Black.copy(.20f),Offset(c.x-r*.92f,c.y+r*.50f),Size(r*1.84f,r*.26f));drawCircle(Color.White.copy(.18f),r*.96f,c-Offset(0f,r*.15f))
   drawCircle(edge,r*.94f,c-Offset(0f,r*.17f))
   if(theme==BoardTheme.PREMIUM_WOOD){drawCircle(materialBrush,r*.94f,c);drawCircle(base.copy(.38f),r*.94f,c)}
   drawCircle(Brush.radialGradient(listOf(Color.White.copy(if(white).62f else .38f),base,edge),c-Offset(r*.30f,r*.42f),r*1.30f),r*.89f,c-Offset(0f,r*.10f))
   drawCircle(Color.White.copy(.46f),r*.87f,c-Offset(0f,r*.10f),style=Stroke(r*.065f));drawCircle(Color.Black.copy(.34f),r*.74f,c-Offset(0f,r*.10f),style=Stroke(r*.070f));drawCircle(Color.White.copy(.20f),r*.65f,c-Offset(0f,r*.10f),style=Stroke(r*.035f));val hollow=c-Offset(0f,r*.10f);drawCircle(Brush.radialGradient(listOf(base.copy(.94f),base.copy(.82f),Color.Black.copy(.40f)),hollow-Offset(r*.10f,r*.10f),r*.54f),r*.47f,hollow);drawArc(Color.Black.copy(.38f),190f,160f,false,Offset(hollow.x-r*.48f,hollow.y-r*.48f),Size(r*.96f,r*.96f),style=Stroke(r*.055f));drawArc(Color.White.copy(.18f),10f,160f,false,Offset(hollow.x-r*.45f,hollow.y-r*.45f),Size(r*.90f,r*.90f),style=Stroke(r*.035f));for(g in -2..2){val yy=c.y-r*.10f+g*r*.16f;val span=sqrt(max(0f,r*r*.48f-(yy-(c.y-r*.10f)).pow(2)));drawLine((if(white)Color(0xff80582f)else Color(0xffc08255)).copy(.12f),Offset(c.x-span,yy),Offset(c.x+span,yy+sin(g*1.8f)*r*.05f),r*.025f)}
   drawOval(Color.White.copy(.42f),Offset(c.x-r*.44f,c.y-r*.49f),Size(r*.44f,r*.18f))
   if(available&&!on){drawCircle(Color(0xffb7f45c).copy(.30f+.22f*pulse),r*1.15f,c);drawCircle(Color(0xff9ee84e),r*1.12f,c,style=Stroke(4f))};if(on){drawCircle(Color.Black.copy(.42f),r*1.13f,c,style=Stroke(7f));drawCircle(p.accent,r*1.13f,c,style=Stroke(4f))}
  }
  val active=motion
  for(pt in 0..23){val n=abs(state.position.points[pt]);for(i in 0 until min(n,5)){if(active?.to==pt&&i==min(n,5)-1)continue;piece(center(pt,i),cw*.262f,state.position.points[pt]>0,selected==pt&&i==min(n,5)-1,legal.any{it.from==pt}&&i==min(n,5)-1)};if(n>5)drawCircle(p.accent,cw*.18f,center(pt,4))}
  if(active?.to!=Move.BAR){val br=cw*.238f;for(i in 0 until min(state.position.barWhite,8))piece(Offset(barLeft+barW/2,size.height*.57f+i*br*.48f),br,true,selected==Move.BAR&&i==min(state.position.barWhite,8)-1,legal.any{it.from==Move.BAR}&&i==min(state.position.barWhite,8)-1);for(i in 0 until min(state.position.barBlack,8))piece(Offset(barLeft+barW/2,size.height*.43f-i*br*.48f),br,false,selected==Move.BAR&&i==min(state.position.barBlack,8)-1,legal.any{it.from==Move.BAR}&&i==min(state.position.barBlack,8)-1)}
  fun DrawScope.offChip(y:Float,white:Boolean){val chipW=trayW*.68f;val chipH=((trayH-16f)/15f)*.66f;val base=if(white)Color(0xffe2c58d)else Color(0xff603326);drawRoundRect(Color.Black.copy(.38f),Offset(trayX+(trayW-chipW)/2+1f,y+2f),Size(chipW,chipH),CornerRadius(chipH/2));drawRoundRect(Brush.verticalGradient(listOf(Color.White.copy(.42f),base,base.copy(.72f))),Offset(trayX+(trayW-chipW)/2,y),Size(chipW,chipH),CornerRadius(chipH/2));drawLine(Color.White.copy(.30f),Offset(trayX+(trayW-chipW)/2+3f,y+2f),Offset(trayX+(trayW+chipW)/2-3f,y+2f),1f)};val chipStep=(trayH-16f)/15f;for(i in 0 until state.position.offBlack)offChip(rail*2.2f+8f+i*chipStep,false);for(i in 0 until state.position.offWhite)offChip(size.height-rail*2.2f-8f-(i+1)*chipStep,true)
  active?.let{m->
   fun endpoint(point:Int,start:Boolean):Offset=when(point){Move.BAR->Offset(barLeft+barW/2,if(m.white)size.height*.62f else size.height*.38f);Move.OFF->Offset(playRight+(size.width-playRight)/2,if(m.white)size.height*.68f else size.height*.32f);else->{val count=if(start)abs(previous.points[point])else abs(state.position.points[point]);center(point,(count-1).coerceAtLeast(0))}}
   val a=endpoint(m.from,true);val b=endpoint(m.to,false);val q=travel.value*travel.value*(3f-2f*travel.value);val moving=Offset(a.x+(b.x-a.x)*q,a.y+(b.y-a.y)*q);val lift=sin(Math.PI.toFloat()*q);drawOval(Color.Black.copy(.25f-.11f*lift),Offset(moving.x-cw*(.25f+.04f*lift),moving.y+cw*(.19f+.07f*lift)),Size(cw*(.50f+.08f*lift),cw*(.15f+.03f*lift)));piece(moving,cw*(.272f+.014f*lift),m.white,true)
  }
  legal.filter{it.from==selected}.forEach{m->val c=if(m.to==Move.OFF)Offset(playRight+(size.width-playRight)/2,size.height/2)else center(m.to,abs(state.position.points[m.to]).coerceAtMost(4));val arrow=Path().apply{moveTo(c.x,c.y-cw*.32f);lineTo(c.x+cw*.30f,c.y+cw*.25f);lineTo(c.x+cw*.10f,c.y+cw*.19f);lineTo(c.x,c.y+cw*.38f);lineTo(c.x-cw*.10f,c.y+cw*.19f);lineTo(c.x-cw*.30f,c.y+cw*.25f);close()};drawPath(arrow,Color(0xffffd43b).copy(.68f+.28f*pulse));drawPath(arrow,Color(0xff4a2b00),style=Stroke(2.2f))}
  drawLine(Color.White.copy(.2f),Offset(rail,size.height/2),Offset(playRight,size.height/2),2f)
 }
}
